// Function declarations shared between UBPD modules.
// The Arduino builder used to generate these with ctags; main/ is now built
// by IDF as several .cpp files, so the declarations are explicit here.
// Add a line here when a new function is called from another module.
#pragma once

#include "config.h"

void setup();
void loop();
void classicLabel(const ClassicDevice *d, char *out, size_t maxChars);
void classicScanStart();
void classicScanStop();
void classicTick();
void forgetStaleClassic();
void buildClassicList();
int16_t classicOrderIndexOf(const uint8_t *addr);
int16_t classicLookupByAddr(const uint8_t *addr);
void toggleFavoriteClassic(int16_t clsIdx);
void buzzerInit();
void buzzerApplyIdle();
void buzzerPlay(uint8_t count);
void buzzerSilence();
void buzzerTest();
void buzzerTick();
void layoutCompute();
uint8_t listRows();
int16_t rowTop(uint8_t row);
int16_t rowBaseline(uint8_t row);
void displayInit();
void splashScreen();
void txt(int16_t x, int16_t y, const char *s);
int16_t txtW(const char *s);
void txtCenter(int16_t y, const char *s);
void toast(const char *msg, uint16_t ms);
void drawHeader(const char *title, const char *right);
void drawFooter(const char *hint);
void drawRow(uint8_t row, const char *left, const char *right, bool sel);
void drawTextScreen(const char *title, const char *right, const char *body, const char *hint);
void pushBtnEvent(uint8_t ev);
bool btnEventPop(uint8_t *ev);
void pollButtons();
void pollSerialControl();
void printHelp();
void ledPulse(uint16_t ms);
void pollLed();
float batteryVoltage();
int batteryPercent();
const char * batteryLabel();
float chipTemperature();
void hardwareInit();
void setError(const char *msg);
const char * uptimeLabel();
void buildRadarPoints();
void radarTick();
void drawRadarOverlay();
void drawRadarScreen();
void handleRadar(uint8_t ev);
const char * kindTag(uint8_t kind, uint8_t conf, char *buf, size_t bufLen);
const char * companyShort(uint16_t cid);
void bleScanStart();
void bleScanStop();
void bleScanRecycle();
void forgetStaleDevices();
void buildSortedDeviceList();
void buildCombinedList();
int16_t scanOrderIndexOf(const uint8_t *addr);
bool deviceAddrSnapshot(int16_t idx, uint8_t *out);
void deviceLabel(const BleDevice *d, char *out, size_t maxChars);
void macLabel(const uint8_t *addr, char *out, size_t outLen);
int16_t findFavIndex(const uint8_t *addr);
bool isFavorite(const uint8_t *addr);
void toggleFavorite(int16_t devIdx);
void connLine(const char *s);
bool bleConnect(const uint8_t *addr);
void bleDisconnect();
void advStart(const char *nameUtf8);
void advStop();
void wifiScanStart();
void wifiScanStop();
void wifiRadioOff();
void wifiScanPoll();
void sleepStart();
void sleepStop();
void sleepTick();
void storageSaveFavorites();
void storageSaveSettings();
void storageLoad();
void storageReset();
int favCount();
// Wi-Fi на esp-idf вместо Arduino-класса WiFi (wifi.cpp)
bool wifiIsReady();
void wifiStart();
bool apStart(const char *ssid, const char *pass, bool open);
void apStop();
bool apIsUp();
const char * apIpString();
int apClientCount();
const char * typeNameAt(uint8_t t);
const char * identNameAt(uint8_t i);
uint8_t identNameCount();
const char * funNameAt(uint8_t i);
uint8_t funNameCount();
const char * funModeName(uint8_t m);
void uiInit();
const char * identityAdvName();
bool bgAllows(uint8_t func);
bool sleepAllows(uint8_t func);
const char * bgStateName(uint8_t st);
void syncRadios();
void enterScreen(Screen s);
void uiLoop();
void screenTick();
void clampList();
void handleEvent(uint8_t ev);
void handleMenu(uint8_t ev);
void openMenuItem();
void openDeviceScreen(int16_t devIdx, Screen from);
void clampComb();
void handleScanners(uint8_t ev);
void handleScanner(uint8_t ev);
void handleBleScan(uint8_t ev);
void handleDevice(uint8_t ev);
int16_t favRssi(int16_t slot);
void handleWatch(uint8_t ev);
void handleIdentity(uint8_t ev);
void bleFunTick();
void handleBleFun(uint8_t ev);
void timedTick();
void handleTimed(uint8_t ev);
void handleType(uint8_t ev);
void handleSleep(uint8_t ev);
void handleSettings(uint8_t ev);
void clampClassicList();
void handleClassic(uint8_t ev);
void handleClassicDev(uint8_t ev);
void handleManager(uint8_t ev);
void handleBgSet(uint8_t ev);
void handleWeb(uint8_t ev);
void handlePcRemote(uint8_t ev);
// PC REMOTE: Bluetooth SPP-сервер + JSON (pcremote.cpp)
void pcRemoteInit();
void pcRemoteSend(const char *s);
bool pcRemoteConnected();
// SD-карта (sdcard.cpp)
void sdInit();
bool sdMounted();
const char *sdCardInfo();
void sdListDir(const char *path);
// REMOTE: A2DP-плеер (player.cpp)
void playerInit();
bool playerConnect(const uint8_t *bda);
void playerPlay();
void playerStop();
void playerDisconnect();
bool playerLoadWav(const char *path);
void playerUseTone();
bool playerConnected();
bool playerPlaying();
void playerScanTracks();
bool playerPlayTrack(uint8_t idx);
void playerPlayRandom();
void playerNextTrack();
uint8_t playerTrackCount();
const char *playerTrackName(uint8_t i);
uint8_t playerCurrentTrack();
void avrcInit();
void avrcPlayPause();
void avrcNext();
void avrcPrev();
void avrcVolUp();
void avrcVolDown();
void handleRemote(uint8_t ev);
void drawCurrentScreen();
void webInit();
void webStop();
void webTick();
bool webIsRunning();
const char * webApSsid();
